<?xml version="1.0" encoding="GB2312" standalone="yes" ?>
<!DOCTYPE UserExceptions [
  <!ELEMENT UserExceptions      (UserException+)>
  <!ELEMENT UserException       (Error+,ErrorCatalog,Description)>
  <!ELEMENT Error               (ErrorNo,ErrorMessage)>
  <!ELEMENT ErrorCatalog        (#PCDATA)>
  <!ELEMENT Description         (#PCDATA)>
  <!ELEMENT ErrorNo             (#PCDATA)>
  <!ELEMENT ErrorMessage        (#PCDATA)>
]>

<UserExceptions>
  <UserException ErrorCatalog="-1" Description="OS">
  </UserException>
  <UserException ErrorCatalog="-2" Description="NET">
  </UserException>
  <UserException ErrorCatalog="-3" Description="DATABASE">
    <Error>
      <ErrorNo>200</ErrorNo>
      <ErrorMessage>无满足条件的记录</ErrorMessage>
    </Error>
    <Error>
      <ErrorNo>-201</ErrorNo>
      <ErrorMessage>SQL语句有语法错误 </ErrorMessage>
    </Error>
  </UserException>
  <UserException ErrorCatalog="-4" Description="MIDWARE">
  </UserException>
  <UserException ErrorCatalog="-5" Description="PROGRAM">
  </UserException>
  <UserException ErrorCatalog="-98" Description="APPLICATION">
        <Error>
           <ErrorNo>-1000</ErrorNo>
           <ErrorMessage>分保通知不存在</ErrorMessage>
        </Error>
        <Error>
           <ErrorNo>-1001</ErrorNo>
           <ErrorMessage>用于测试 </ErrorMessage>
        </Error>
      <Error>
        <ErrorNo>-901</ErrorNo>
        <ErrorMessage>指定的记录起始位置，超出了满足条件结果集的记录数</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-902</ErrorNo>
        <ErrorMessage>用户名或密码错误，请重新登录</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-903</ErrorNo>
        <ErrorMessage>该用户没有正确设置岗位权限，请系统管理员检查该用户在PrpUserGrade表中的岗位设置</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-904</ErrorNo>
        <ErrorMessage>无此用户</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-996</ErrorNo>
        <ErrorMessage>不存在该配置项</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-997</ErrorNo>
        <ErrorMessage>参数值为空</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-999</ErrorNo>
        <ErrorMessage>Config类没有初始化</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-1010</ErrorNo>
        <ErrorMessage>您的登录账号闲置时间过长，为了安全起见，系统已经注销了用户的登录信息，请重新登录。</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-1011</ErrorNo>
        <ErrorMessage>没有设置SelfPage参数</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-1012</ErrorNo>
        <ErrorMessage>非字符型字段不允许使用通配符进行查询 </ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-1013</ErrorNo>
        <ErrorMessage>非法的日期格式</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-1014</ErrorNo>
        <ErrorMessage>非法的数值格式</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-1015</ErrorNo>
        <ErrorMessage>查询条件按照|(或)、:(区间)时，格式不正确</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-1016</ErrorNo>
        <ErrorMessage>配置文件config.xml中的配置项TOP_COMPANY有误 </ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-1017</ErrorNo>
        <ErrorMessage>用户代码表中没有定义该用户名的代码</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-1018</ErrorNo>
        <ErrorMessage>用户没有相应的查询权限</ErrorMessage>
      </Error>
	  <Error>
        <ErrorNo>-1020</ErrorNo>
        <ErrorMessage>用户没有相应的操作权限</ErrorMessage>
      </Error>

      <Error>
        <ErrorNo>-1101</ErrorNo>
        <ErrorMessage>查找再保确认表相关数据失败</ErrorMessage>
      </Error>

      <Error>
        <ErrorNo>-2001</ErrorNo>
        <ErrorMessage>该合约有分项信息存在，不能删除</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-2002</ErrorNo>
        <ErrorMessage>非暂存状态的合约及其分项只能查看</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-3001</ErrorNo>
        <ErrorMessage>所删除的保单已经进行了批改</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-3002</ErrorNo>
        <ErrorMessage>所删除的保单已经生成了赔案</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-3003</ErrorNo>
        <ErrorMessage>所删除的保单已经生成分保单</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-3004</ErrorNo>
        <ErrorMessage>根据分保通知号获取保单信息失败</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-3005</ErrorNo>
        <ErrorMessage>分保单没有临分</ErrorMessage>
      </Error>

      <Error>
        <ErrorNo>-4001</ErrorNo>
        <ErrorMessage>获取分保单信息失败</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-4002</ErrorNo>
        <ErrorMessage>获取原始分保单的临分信息失败</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-4003</ErrorNo>
        <ErrorMessage>获取原始分保单的金额合计信息失败</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-4004</ErrorNo>
        <ErrorMessage>根据分保通知号获取保单标的信息失败</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-4005</ErrorNo>
        <ErrorMessage>没有要打印的数据</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-4006</ErrorNo>
        <ErrorMessage>获取分保摘要信息失败</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-4007</ErrorNo>
        <ErrorMessage>该保单已经生成分保单，不能再生成分保单</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-4008</ErrorNo>
        <ErrorMessage>分保单已经复核，不能再复核</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-5001</ErrorNo>
        <ErrorMessage>所删除的批单已经生成了分批单</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-5002</ErrorNo>
        <ErrorMessage>所删除的批单已经生效</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-5003</ErrorNo>
        <ErrorMessage>所删除的批单已经有了赔案</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-5004</ErrorNo>
        <ErrorMessage>根据分保通知号获取批单信息失败</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-5005</ErrorNo>
        <ErrorMessage>根据分保通知号获取批单标的信息失败</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-5006</ErrorNo>
        <ErrorMessage>该批单已经生成分批单，不能再生成分批单</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-5007</ErrorNo>
        <ErrorMessage>存在未复核的分保单，不能生成分批单</ErrorMessage>
      </Error>
        <Error>
        <ErrorNo>-5008</ErrorNo>
        <ErrorMessage>批单所批分保通知号不同属于一张分保单</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-6001</ErrorNo>
        <ErrorMessage>获取分批单主表信息失败</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-6002</ErrorNo>
        <ErrorMessage>获取临分安排信息失败</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-6003</ErrorNo>
        <ErrorMessage>根据分批单号取分批单金额合计信息失败</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-6004</ErrorNo>
        <ErrorMessage>没有要打印的数据</ErrorMessage>
      </Error>

      <Error>
        <ErrorNo>-7001</ErrorNo>
        <ErrorMessage>所要删除的赔案已经生成了分赔案</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-7002</ErrorNo>
        <ErrorMessage>赔案对应保单未分保，不能生成分赔案</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-7003</ErrorNo>
        <ErrorMessage>此赔案前有赔案未分摊，不能生成分赔案</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-7004</ErrorNo>
        <ErrorMessage>出险前对应的各张分批单未分保，不能生成分赔案</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-7005</ErrorNo>
        <ErrorMessage>出险前对应的分批单未复核，不能生成分赔案</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-7006</ErrorNo>
        <ErrorMessage>获取赔案信息失败</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-7007</ErrorNo>
        <ErrorMessage>取分赔案号失败</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-7008</ErrorNo>
        <ErrorMessage>生成分赔案主信息失败</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-7009</ErrorNo>
        <ErrorMessage>所要删除的赔案不是最后一张赔案，不能删除</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-7010</ErrorNo>
        <ErrorMessage>没有要打印的数据</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-7011</ErrorNo>
        <ErrorMessage>与赔案对应的保单还没进行分保安排 </ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-7012</ErrorNo>
        <ErrorMessage>赔案对应的分保单未复核，不能生成分赔案</ErrorMessage>
      </Error>

      <Error>
        <ErrorNo>-8001</ErrorNo>
        <ErrorMessage>获取分赔案主信息失败</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-8002</ErrorNo>
        <ErrorMessage>获取分保主信息失败</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-8003</ErrorNo>
        <ErrorMessage>分保单（分批单）未复核</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-8004</ErrorNo>
        <ErrorMessage>获取共保人信息失败</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-8005</ErrorNo>
        <ErrorMessage>获取分保信息失败</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-8006</ErrorNo>
        <ErrorMessage>获取分保摘要信息失败</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-8007</ErrorNo>
        <ErrorMessage>分赔案还未分摊</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-8008</ErrorNo>
        <ErrorMessage>分赔案已经复核</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-8009</ErrorNo>
        <ErrorMessage>获取赔案分摊信息失败</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-8010</ErrorNo>
        <ErrorMessage>获取保单的共保信息失败</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-8011</ErrorNo>
        <ErrorMessage>获取分保单的共保信息失败</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-8012</ErrorNo>
        <ErrorMessage>获取赔案分摊摘要信息失败</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-8013</ErrorNo>
        <ErrorMessage>生成合计收/付款计划信息失败</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-8014</ErrorNo>
        <ErrorMessage>生成分保业务明细信息失败</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-8015</ErrorNo>
        <ErrorMessage>生成对内收/付款计划信息失败</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-8016</ErrorNo>
        <ErrorMessage>该分保赔案有对外帐单生成，不能复核作废 </ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-8017</ErrorNo>
        <ErrorMessage>该分保赔案有对内帐单生成，不能复核作废 </ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-8018</ErrorNo>
        <ErrorMessage>获取分保赔案的金额合计信息失败</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-8019</ErrorNo>
        <ErrorMessage>该分保赔案没有临分已决赔款信息</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-8020</ErrorNo>
        <ErrorMessage>该分保赔案没有临分接受人 </ErrorMessage>
      </Error>

      <Error>
        <ErrorNo>-9001</ErrorNo>
        <ErrorMessage>获取帐单信息失败</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9002</ErrorNo>
        <ErrorMessage>该帐单已经转财务不可以删除</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9003</ErrorNo>
        <ErrorMessage>本赔案的内外帐在不同的帐单期，请修正</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9004</ErrorNo>
        <ErrorMessage>本赔案尚未生成现金赔款帐单</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9005</ErrorNo>
        <ErrorMessage>获取帐单项目信息失败</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9006</ErrorNo>
        <ErrorMessage>内外帐单项目金额有差异</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9007</ErrorNo>
        <ErrorMessage>帐单已转财务 </ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9008</ErrorNo>
        <ErrorMessage>取临分帐单信息失败</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9009</ErrorNo>
        <ErrorMessage>不存在临分对内账单</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9010</ErrorNo>
        <ErrorMessage>不存在临分对外账单</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9011</ErrorNo>
        <ErrorMessage>生成记帐凭证号失败</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9012</ErrorNo>
        <ErrorMessage>根据帐单号取帐单结付计划主表信息失败</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9013</ErrorNo>
        <ErrorMessage>获取会计月度信息失败</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9014</ErrorNo>
        <ErrorMessage>获取预约凭证号信息失败</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9015</ErrorNo>
        <ErrorMessage>根据帐单号取帐单结付计划详细信息失败</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9016</ErrorNo>
        <ErrorMessage>无需生成合同对内帐单</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9017</ErrorNo>
        <ErrorMessage>无需生成合同对外帐单</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9018</ErrorNo>
        <ErrorMessage>未找到此帐单期下的合同对内帐单，不能生成合同对外帐单</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9019</ErrorNo>
        <ErrorMessage>复核作废失败，请删除对外帐单后再复核作废 </ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9020</ErrorNo>
        <ErrorMessage>复核作废失败，请删除对内帐单后再复核作废 </ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9021</ErrorNo>
        <ErrorMessage>此分批单已生成分赔案，请先删除分赔案</ErrorMessage>
      </Error>

      <Error>
        <ErrorNo>-9022</ErrorNo>
        <ErrorMessage>分批单对应的分保单存在其它未生效的分批单</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9023</ErrorNo>
        <ErrorMessage>只能作废最近一张分批单</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9024</ErrorNo>
        <ErrorMessage>此次分保安排中，没有合同分保方式的安排 </ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9025</ErrorNo>
        <ErrorMessage>该帐单期已经生成帐单，不能调整应付日期</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9026</ErrorNo>
        <ErrorMessage>该帐单已经是冲销帐单，不能再次冲销</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9027</ErrorNo>
        <ErrorMessage>该帐单已经做过冲销帐单，不能再次冲销</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9028</ErrorNo>
        <ErrorMessage>该帐单还没有转财务，不用冲销</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9029</ErrorNo>
        <ErrorMessage>获取帐单号失败</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9030</ErrorNo>
        <ErrorMessage>获取帐单项目代码信息失败</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9031</ErrorNo>
        <ErrorMessage>科目与帐单项目缺少对应关系 </ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9032</ErrorNo>
        <ErrorMessage>该帐单不是冲销帐单，不用转财务 </ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9033</ErrorNo>
        <ErrorMessage>已经生成分批单，不能复核作废 </ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9034</ErrorNo>
        <ErrorMessage>已经生成分赔案，不能复核作废 </ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9035</ErrorNo>
        <ErrorMessage>该帐单已经生成冲销帐单，不能删除</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9036</ErrorNo>
        <ErrorMessage>此分保单已经发生批改，请删除分批单后作废复核！</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9037</ErrorNo>
        <ErrorMessage>不存在对应业务帐单，不用转财务</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9038</ErrorNo>
        <ErrorMessage>该帐单已经转财务不可以修改</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9039</ErrorNo>
        <ErrorMessage>此分保单已经生成帐单，不能复核作废</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9040</ErrorNo>
        <ErrorMessage>已经生成过明细帐单，无需再次生成</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9041</ErrorNo>
        <ErrorMessage>无需生成分期差额帐</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9042</ErrorNo>
        <ErrorMessage>无需生成明细预估帐</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9043</ErrorNo>
        <ErrorMessage>无需生成尾差差额帐</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9044</ErrorNo>
        <ErrorMessage>分保费不平，请检查原因后再生成尾差差额帐</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9045</ErrorNo>
        <ErrorMessage>还未生成明细帐单，不能做帐单确认</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9046</ErrorNo>
        <ErrorMessage>无需做帐单确认</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9047</ErrorNo>
        <ErrorMessage>还有未做帐的业务，请先生成帐单</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9048</ErrorNo>
        <ErrorMessage>没有保费或赔款，无需生成临分帐单</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9049</ErrorNo>
        <ErrorMessage>没有已决赔款，无需生成现金赔款帐单</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9050</ErrorNo>
        <ErrorMessage>对外帐单已经生成</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9051</ErrorNo>
        <ErrorMessage>帐单已经生成，无需再次生成</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9052</ErrorNo>
        <ErrorMessage>该合约当前账期无业务数据，无需生成账单</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9054</ErrorNo>
        <ErrorMessage>收付款计划存在未生成月度帐的数据</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-9053</ErrorNo>
        <ErrorMessage>帐单批量生成</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-12001</ErrorNo>
        <ErrorMessage>获取合同主信息失败</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-12002</ErrorNo>
        <ErrorMessage>根据合同序号取合同接受人表信息失败</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-12003</ErrorNo>
        <ErrorMessage>根据合同序号取合同利益表信息失败</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-12004</ErrorNo>
        <ErrorMessage>没有要打印的数据</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-12005</ErrorNo>
        <ErrorMessage>合同分保接受人总的接受份额(成数合同加自留比例)不足100％</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-12006</ErrorNo>
        <ErrorMessage>合同分保接受人总的接受份额(成数合同加自留比例)超过100％</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-12007</ErrorNo>
        <ErrorMessage>合同未生效不可续转</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-12008</ErrorNo>
        <ErrorMessage>合同已注销不可续转</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-12009</ErrorNo>
        <ErrorMessage>合同已生效</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-12010</ErrorNo>
        <ErrorMessage>合同已注销</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-12011</ErrorNo>
        <ErrorMessage>合同未生效不用注销</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-12012</ErrorNo>
        <ErrorMessage>合同已经生效或者被注销不能再编辑</ErrorMessage>
      </Error>

      <Error>
        <ErrorNo>-20001</ErrorNo>
        <ErrorMessage>你可能已经进行过初始化了 </ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-20002</ErrorNo>
        <ErrorMessage>系统升级更新数据表出错</ErrorMessage>
      </Error>
      <Error>
           <ErrorNo>-20003</ErrorNo>
           <ErrorMessage>输入的密码与原密码不一致 </ErrorMessage>
      </Error>
      <Error>
           <ErrorNo>-20004</ErrorNo>
           <ErrorMessage>主保单号不能为空</ErrorMessage>
      </Error>
      <Error>
           <ErrorNo>-20005</ErrorNo>
           <ErrorMessage>系统可能没有进行单号初始化，请系统管理员维护</ErrorMessage>
      </Error>
      <Error>
           <ErrorNo>-20006</ErrorNo>
           <ErrorMessage>取不到单号描述信息，请系统管理员维护</ErrorMessage>
      </Error>

      <Error>
           <ErrorNo>-21001</ErrorNo>
           <ErrorMessage>按主键查询分入分保单信息失败</ErrorMessage>
      </Error>
      <Error>
           <ErrorNo>-21002</ErrorNo>
           <ErrorMessage>该分入分保单信息未复核</ErrorMessage>
      </Error>
      <Error>
           <ErrorNo>-21003</ErrorNo>
           <ErrorMessage>该分入分保单已经转分保，不允许再次转送</ErrorMessage>
      </Error>

      <Error>
           <ErrorNo>-22001</ErrorNo>
           <ErrorMessage>按主键查询分入分批单信息失败</ErrorMessage>
      </Error>
      <Error>
           <ErrorNo>-22002</ErrorNo>
           <ErrorMessage>该分入分批单信息未复核</ErrorMessage>
      </Error>
      <Error>
           <ErrorNo>-22003</ErrorNo>
           <ErrorMessage>该分入分批单已经转分保，不允许再次转送</ErrorMessage>
      </Error>
      <Error>
           <ErrorNo>-22004</ErrorNo>
           <ErrorMessage>查询该分入分批单对应的分入分保单信息失败</ErrorMessage>
      </Error>
      <Error>
           <ErrorNo>-22005</ErrorNo>
           <ErrorMessage>该分入分批单对应的分入分保单还没有转分保 </ErrorMessage>
      </Error>
      <Error>
           <ErrorNo>-22006</ErrorNo>
           <ErrorMessage>该分入分批单对应的分出保单还没有分保 </ErrorMessage>
      </Error>
      <Error>
           <ErrorNo>-22007</ErrorNo>
           <ErrorMessage>该分入分保单存在未复核的分批单，不能新增分批单</ErrorMessage>
      </Error>
      <Error>
           <ErrorNo>-23001</ErrorNo>
           <ErrorMessage>按主键查询分入分赔案信息失败</ErrorMessage>
      </Error>
      <Error>
           <ErrorNo>-23002</ErrorNo>
           <ErrorMessage>该分入分赔案信息未复核</ErrorMessage>
      </Error>
      <Error>
           <ErrorNo>-23003</ErrorNo>
           <ErrorMessage>该分入分赔案已经转分保，不允许再次转送</ErrorMessage>
      </Error>
      <Error>
           <ErrorNo>-23004</ErrorNo>
           <ErrorMessage>查询该分入分赔案对应的分入分保单信息失败</ErrorMessage>
      </Error>
      <Error>
           <ErrorNo>-23005</ErrorNo>
           <ErrorMessage>该分入分赔案对应的分入分保单还没有转分保 </ErrorMessage>
      </Error>
      <Error>
           <ErrorNo>-23006</ErrorNo>
           <ErrorMessage>运输工具代码为空不能生成报表 </ErrorMessage>
      </Error>
      <Error>
           <ErrorNo>-23007</ErrorNo>
           <ErrorMessage>该分保业务没有临分信息，不能生成帐单 </ErrorMessage>
      </Error>
       <Error>
           <ErrorNo>-23008</ErrorNo>
           <ErrorMessage>该危险单位已经生成分保单，不能再生成 </ErrorMessage>
      </Error>
       <Error>
           <ErrorNo>-23009</ErrorNo>
           <ErrorMessage>该分赔案为立案信息不需要打印比例拆分单 </ErrorMessage>
      </Error>
       <Error>
           <ErrorNo>-23010</ErrorNo>
           <ErrorMessage>不能生成分批单，请先生成分保单 </ErrorMessage>
      </Error>
       <Error>
           <ErrorNo>-23011</ErrorNo>
           <ErrorMessage>不能生成分批单，请先复核分保单 </ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-23012</ErrorNo>
        <ErrorMessage>此分保单已经发生赔案，请删除分赔案后作废复核！</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-23013</ErrorNo>
        <ErrorMessage>此分批单已经发生赔案，请删除分赔案后作废复核！</ErrorMessage>
      </Error>
       <Error>
        <ErrorNo>-23014</ErrorNo>
        <ErrorMessage>请先完成保单的分保处理，再将立案提交再保！</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-24001</ErrorNo>
        <ErrorMessage>从blAccMonthTrace表中获取数据失败！</ErrorMessage>
      </Error>
       <Error>
        <ErrorNo>-24002</ErrorNo>
        <ErrorMessage>询价单对应的分保单已经生成临分帐单！</ErrorMessage>
      </Error>
       <Error>
        <ErrorNo>-24003</ErrorNo>
        <ErrorMessage>询价单对应的批单保额保费变化不为零或风险评估信息发生变化！</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-24004</ErrorNo>
        <ErrorMessage>询价单对应的保单还没有核保通过！</ErrorMessage>
      </Error>
      <Error>
      <ErrorNo>-24005</ErrorNo>
        <ErrorMessage>询价单对应的批单还没有核保通过！</ErrorMessage>
      </Error>
       <Error>
      <ErrorNo>-24006</ErrorNo>
        <ErrorMessage>询价单对应的分保单还没有复核！</ErrorMessage>
      </Error>
       <Error>
      <ErrorNo>-24007</ErrorNo>
        <ErrorMessage>询价单对应的分批单还没有复核！</ErrorMessage>
      </Error>
       <Error><ErrorNo>-24008</ErrorNo>
        <ErrorMessage>再保送收付失败！</ErrorMessage>
      </Error>
      <Error>
      <ErrorNo>-24009</ErrorNo>
        <ErrorMessage>找不到核算单位，请进行配置！</ErrorMessage>
      </Error>
      <Error>
      <ErrorNo>-24010</ErrorNo>
        <ErrorMessage>没有需要送收付的数据！</ErrorMessage>
      </Error>
      <Error>
      <ErrorNo>-24011</ErrorNo>
      <ErrorMessage>请检查帐单期录入是否合法，谢谢。</ErrorMessage>
      </Error>
       <Error>
      <ErrorNo>-25001</ErrorNo>
        <ErrorMessage>险种代码数据维护不正确，请维护险种代码信息。</ErrorMessage>
      </Error>
      <Error>
      <ErrorNo>-26001</ErrorNo>
        <ErrorMessage>帐单期维护不正确，请维护一个开门帐单期。</ErrorMessage>
      </Error>
      <Error>
      <ErrorNo>-26002</ErrorNo>
        <ErrorMessage>帐单期维护不正确，存在两个以上开门帐单期。</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-26003</ErrorNo>
        <ErrorMessage>存在跳帐单期操作，请按顺序做帐。 </ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-26004</ErrorNo>
        <ErrorMessage>对应帐单期信息未维护，请维护对应帐单期的起止日期。 </ErrorMessage>
      </Error>
      <Error>
      <ErrorNo>-27001</ErrorNo>
        <ErrorMessage>请先完成此分保业务的合约手工调整，再进行分保复核！</ErrorMessage>
      </Error>
       <Error>
        <ErrorNo>-28001</ErrorNo>
        <ErrorMessage>存在未复核的分保单，不能复核</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-28002</ErrorNo>
        <ErrorMessage>存在之前批改的未复核的分批单，不能复核</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-28003</ErrorNo>
        <ErrorMessage>存在已复核的后续分批单，请按顺序进行复核作废</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-28004</ErrorNo>
        <ErrorMessage>存在已复核的后续分赔案，请按顺序进行复核作废</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-28005</ErrorNo>
        <ErrorMessage>分保单还未生成，批单不能临分确认</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-28006</ErrorNo>
        <ErrorMessage>前次批改的分批单还未生成，本次批单不能临分确认</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-28007</ErrorNo>
        <ErrorMessage>此保单已做过批改,请调整最后一笔批单</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-28008</ErrorNo>
        <ErrorMessage>此批单不是最后一次批改，请调整最后一笔批单</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-28009</ErrorNo>
        <ErrorMessage>请先建立对外帐单！</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-28010</ErrorNo>
        <ErrorMessage>该分保业务已经结算，不允许调整！</ErrorMessage>
      </Error>      
	  <Error>
        <ErrorNo>-29001</ErrorNo>
        <ErrorMessage>截止本帐单期纯益手续费帐单已经生成，不能再次生成！</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-29002</ErrorNo>
        <ErrorMessage>还未到纯益手续费帐单规定的起算日期，不能生成帐单！</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-29003</ErrorNo>
        <ErrorMessage>存在未转收付的手续费调整帐单，不能生成纯益手续费帐单。</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-29004</ErrorNo>
        <ErrorMessage>存在未生成正常帐单的收/付款计划数据，不能生成手续费调整帐单，请检查数据！</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-29005</ErrorNo>
        <ErrorMessage>合约纯益手续费起算日期早于合约起期，不能生成纯益手续费帐单，请合约检查数据！</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-29006</ErrorNo>
        <ErrorMessage>合约规定日期内的盈余/亏损金额是亏损的，不能生成纯益手续费帐单！</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-29007</ErrorNo>
        <ErrorMessage>本合约为固定手续费方式，不需生成浮动手续费帐单。</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-29008</ErrorNo>
        <ErrorMessage>截止本帐单期手续费调整帐单已经生成，不能再次生成！</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-29009</ErrorNo>
        <ErrorMessage>此合约纯益手续费率为0，无需生成纯益手续费帐单。</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-29010</ErrorNo>
        <ErrorMessage> 未查到帐单期，请维护对应帐单期日期信息。</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-29011</ErrorNo>
        <ErrorMessage> 本年度已生成过手续费调整帐单，不需再次生成。</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-30001</ErrorNo>
        <ErrorMessage>无相关合约数据，请重新确定查询条件。</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-30002</ErrorNo>
        <ErrorMessage>没有帐单数据。</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-31001</ErrorNo>
        <ErrorMessage>数据检查基础数据未维护。</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-31002</ErrorNo>
        <ErrorMessage>审核通过前再保数据检查，请确认再保临分分出确认状态。</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-31003</ErrorNo>
        <ErrorMessage>审核通过前再保数据检查，请确认再保临分分入确认状态。</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-31004</ErrorNo>
        <ErrorMessage>审核通过前再保数据检查，请确认再保是否做风险评估。</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-31005</ErrorNo>
        <ErrorMessage>审核通过前再保数据检查，请确认再保危险单位占比。</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-31006</ErrorNo>
        <ErrorMessage>审核通过前再保数据检查，请确认核心传送业务类型。</ErrorMessage>
      </Error>
        <Error>
      <ErrorNo>-31007</ErrorNo>
        <ErrorMessage>审核通过前再保数据检查，请做再保风险评估。</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-31008</ErrorNo>
        <ErrorMessage>此业务为分入业务，请点击分入确认按钮提交再保。</ErrorMessage>
      </Error>
      <Error>
        <ErrorNo>-31009</ErrorNo>
        <ErrorMessage>审核通过前再保数据检查，超过最大承保能力，请安排临分。</ErrorMessage>
      </Error>
       <Error>
        <ErrorNo>-31010</ErrorNo>
        <ErrorMessage>审核通过前再保数据检查，该保单没有试算信息，请点击分保试算。</ErrorMessage>
      </Error>
       <Error>
        <ErrorNo>-31011</ErrorNo>
        <ErrorMessage>审核通过前再保数据检查，该批单没有试算信息，请点击分批试算。</ErrorMessage>
      </Error>
       <Error>
        <ErrorNo>-31012</ErrorNo>
        <ErrorMessage>审核通过前再保数据检查，该单号有误，请检查数据。</ErrorMessage>
      </Error>
  </UserException>
</UserExceptions>
